name: "debug"
shortDesc: "debug network tool cmd"
command: "bash ./exec.sh"
flags:
  - name: "container"
    shorthand: "c"
    desc: "Container name. If omitted, the first container in the pod will be chosen"
    defValue: ""
  - name: "pod"
    shorthand: "p"
    desc: "Pod name"
    defValue: ""
